<?php global $stations; ?>
<!doctype html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Stacje</title>
</head>
<body>
<h3>Ocena została dodana, zobacz aktualny ranking stacji.</h3>
<table border="1px">
    <thead>
    <tr>
        <th>Nazwa stacji</th>
        <th>Średnia ocena</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($stations as $s): ?>
        <tr>
            <td><a href="./station.php?id=<?= $s->id ?>"><?= $s->name ?></a></td>
            <td><?= $s->rating ?> ★</td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<br>
<a href="./index.php">Powrót do strony głównej</a>
</body>
</html>