<?php global $stations; ?>
<!doctype html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Stacje</title>
</head>
<body>
    <table border="1px">
        <thead>
            <tr>
                <th>Nazwa stacji</th>
                <th>L. wyciągów</th>
                <th>Naśnieżanie</th>
                <th>Oświetlenie</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($stations as $s): ?>
                <tr>
                    <td><a href="./station.php?id=<?= $s->id ?>"><?= $s->name ?></a></td>
                    <td><?= $s->lift_count ?></td>
                    <td><?= $s->snow ?></td>
                    <td><?= $s->light ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</body>
</html>